version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: expensapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    profiles:
      - local

  api_local:
    image: expensapp-api:local
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - db
    profiles:
      - local

  api_dev:
    image: expensapp-api:dev
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    profiles:
      - dev

  api_prod:
    image: expensapp-api:prod
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    profiles:
      - prod
