spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expensapp?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: admin
  application:
    name: expensapp
  # JPA Properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

    # Hibernate ddl auto (create, create-drop, validate, update)
    # CREATE: Cada vez que se inicia la app, crea la tabla
    # CREATE-DROP: Cada vez que se inicia la app, crea la tabla y cuando se detiene la borra
    # VALIDATE: A revisar.
    # UPDATE: Crea la tabla si no existe, pero si existe la actualiza

    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  # security:
  #   oauth2:
  #     resourceserver:
  #       jwt:
  #         jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
firebase:
  admin-sdk-path: ${GOOGLE_APPLICATION_CREDENTIALS}
  api-key: ${FIREBASE_API_KEY}
